### ISSUE TITLE
Demystifying CAP theorem

### ISSUE THREAD

**Issue by Abdennebi** [Sfeir/quarter-backs#17]
### Time slot
- [ ] 5'
- [ ] 10'
- [ ] 15'
- [x] 20'
- [ ] 30'

#### Pre-Talk proposal

- [X] Create a new issue
- [ ] give it a shaky title
- [ ] indicate time slot (20' max) and a short description
- [ ] Assign all speakers
- [ ] select the milestone (qb-YYYYMMdd)
- [ ] select a label (Talk, Hands-On or Request, beginner ...etc)

#### Post Talk
- [ ] add a comment to the issue and add all talk materials (github repository, slides, running demos ...etc)
- [ ] add a comment to give us a feedback

**Comment by abderrazak-bouadma** [comment]
reopen when needed
