### ISSUE TITLE
Refactoring, how to make code great again (based on Martin Fowler’s book)

### ISSUE THREAD

**Issue by artpick** [Sfeir/quarter-backs#19]
### Time slot

- [ ] 5'
- [ ] 10'
- [ ] 15'
- [x] 20'

### Pitch

We all know what is shit code, just let's talk about how to make it great again. Some people have analysed what brings you to that kind of messy situation and most importantly how to make it enjoyable to work with again.
Here I will present some situations and practices, making in perspective Martin Fowler's book.
[Buy the book](https://martinfowler.com/books/refactoring.html)
The book is also available by the :sparkles: Sfeir :sparkles: library.

### Rock Star Check list

- [X] Create a new issue
- [X] give it a shaky title
- [X] indicate time slot (20' max) and a short description
- [X] Assign all speakers
- [X] select the milestone (qb-YYYYMMdd)
- [X] select a label (Talk, Hands-On or Request, beginner ...etc)
- [ ] add a comment to the issue and add all talk materials (github repository, slides, running demos ...etc)
- [ ] add a comment to give us a feedback 

### Some advises

- Try to use simple words
- A picture better than 1000 words
- KISS :kiss:
- try not to use lot of screen switch (we don't provide :cold_sweat: bags)
- have fun and try to interact with your audience.

**Comment by artpick** [comment]
You might want to close that issue too @abderrazak-bouadma

**Comment by abderrazak-bouadma** [comment]
salut @artpick , es-tu interessé de faire ton talk le 21 aout prochain ?

**Comment by artpick** [comment]
Hello @abderrazak-bouadma , ça me parait compliqué pour le 21, si tu me dit septembre je peux voir pour que ça se fasse, là c'est trop proche.

**Comment by abderraza8k** [comment]
@artpick left the company
