### ISSUE TITLE
Docker Swarm vs Kubernetes - Fight !

### ISSUE THREAD

**Issue by zbbfufu** [Sfeir/quarter-backs#41]
### Time slot

- [ ] 5'   (best to introduce a concept, a lib, an algorithm)
- [X] 10'  (best to make a demo talk about a lib, an algorithm,)
- [ ] 15'  (best to talk about any back subject with some slides and may be a lightening demo)
- [ ] 20'  (The ted.com format)

### Pitch

À travers un duel acharné, vous découvrirez les principales fonctionnalités attendues d'un orchestrateur de container et les avantages et inconvénients des deux principaux orchestrateurs du marché : Docker Swarm et Kubernetes.

### Rock Star Check list

- [X] Create a new issue
- [X] give it a shaky title
- [X] indicate time slot (20' max) and a short description
- [ ] Assign all speakers
- [ ] select the milestone (qb-YYYYMMdd)
- [X] select a label (Talk, Hands-On or Request, beginner ...etc)
- [ ] add a comment to the issue and add all talk materials (github repository, slides, running demos ...etc)
- [ ] add a comment to give us a feedback 

### Some advises

- Try to use simple words
- A picture better worth 1000 words
- KISS :kiss:
- try not to use lot of screen switch (we don't provide vomit bags)
- and more especially, have fun and try to interact with your audience.

**Comment by zbbfufu** [comment]
Je cherche un co-speaker qui souhaiterai défendre l'un ou l'autre des orchestrateurs.

**Comment by zbbfufu** [comment]
Ce talk est conçu pour avoir lieu après le #40

**Comment by jpuzzler** [comment]
Salut @zbbfufu , j'ai ajouté ton talk pour Mars, on reçois David Gageot pour parler de Kubernetes, ton talk semble être d'actualité. penses-tu pouvoir le préparer à temps ?

**Comment by zbbfufu** [comment]
Oui, je pense avoir le temps. Ce qui serait génial c'est de faire ce talk
avec David, chacun défendant sa partie (à son choix). Tu peux lui proposer
?

[image: Logo] <https://sfeir.com/> Julien Furgerot - Artisan Développeur
Google Certified Professional - Cloud Architect
<https://www.credential.net/ias3b4gn?key=dd9ef1896c287e8380e37b45e214145d4765a4098d331e4b4054d4888798d83a>
48 rue Jacques Dulud - 92200 Neuilly sur Seine
furgerot.j@sfeir.com


Le 6 février 2018 à 22:46, Abderrazak BOUADMA <notifications@github.com> a
écrit :

**Comment by jpuzzler** [comment]
Je vois ça et je te répond, mais garde en tête de faire le talk quand même
merci à toi
