### ISSUE TITLE
Up: le serverless problemless !

### ISSUE THREAD

**Issue by SiegfriedEhret** [Sfeir/quarter-backs#44]
### Time slot

- [ ] 5'   (best to introduce a concept, a lib, an algorithm)
- [ ] 10'  (best to make a demo talk about a lib, an algorithm,)
- [x] 15'  (best to talk about any back subject with some slides and may be a lightening demo)
- [ ] 20'  (The ted.com format)

### Pitch

Venez découvrir [Up](https://up.docs.apex.sh/), un outil pour déployer sans serveur et sans problème pour plein de possibilités !

![dsjigzevaaaf_ho](https://user-images.githubusercontent.com/537567/35863777-066aa6e4-0b50-11e8-83a9-022a623c4eaf.jpg)

### Rock Star Check list

- [X] Create a new issue
- [x] give it a shaky title
- [x] indicate time slot (20' max) and a short description
- [x] Assign all speakers
- [ ] select the milestone (qb-YYYYMMdd)
- [ ] select a label (Talk, Hands-On or Request, beginner ...etc)
- [ ] add a comment to the issue and add all talk materials (github repository, slides, running demos ...etc)
- [ ] add a comment to give us a feedback 

### Some advises

- Try to use simple words
- A picture better worth 1000 words
- KISS :kiss:
- try not to use lot of screen switch (we don't provide vomit bags)
- and more especially, have fun and try to interact with your audience.

**Comment by jpuzzler** [comment]
Salut @SiegfriedEhret , voudrais-tu inclure ton talk pour la session de Mars (Cloud Native) ?

**Comment by SiegfriedEhret** [comment]
Ça se tente même si à côté d'un David Gageot je ne fais pas le poids ^^

**Comment by abderraza8k** [comment]
@SiegfriedEhret left the company
