### ISSUE TITLE
Premiers pas en Node.JS volume 1

### ISSUE THREAD

**Issue by SiegfriedEhret** [Sfeir/quarter-backs#47]
### Time slot

- [ ] 5'   (best to introduce a concept, a lib, an algorithm)
- [ ] 10'  (best to make a demo talk about a lib, an algorithm,)
- [x] 15'  (best to talk about any back subject with some slides and may be a lightening demo)
- [ ] 20'  (The ted.com format)

### Pitch

On a discuté rapidement de ce que sont Node.JS et npm. Il est maintenant l'heure de mettre les mains dans le cambouis ! Nous allons faire le tour de quelques API classiques de Node.JS, accompagné de démo / livecoding.

### Rock Star Check list

- [X] Create a new issue
- [x] give it a shaky title
- [x] indicate time slot (20' max) and a short description
- [x] Assign all speakers
- [ ] select the milestone (qb-YYYYMMdd)
- [ ] select a label (Talk, Hands-On or Request, beginner ...etc)
- [ ] add a comment to the issue and add all talk materials (github repository, slides, running demos ...etc)
- [ ] add a comment to give us a feedback 

### Some advises

- Try to use simple words
- A picture better worth 1000 words
- KISS :kiss:
- try not to use lot of screen switch (we don't provide vomit bags)
- and more especially, have fun and try to interact with your audience.

**Comment by abderraza8k** [comment]
@SiegfriedEhret left the company
