### ISSUE TITLE
Speechless Live

### ISSUE THREAD

**Issue by jefBinomed** [Sfeir/quarter-backs#54]
### Time slot

- [ ] 5'   (best to introduce a concept, a lib, an algorithm)
- [ ] 10'  (best to make a demo talk about a lib, an algorithm,)
- [ ] 15'  (best to talk about any back subject with some slides and may be a lightening demo)
- [ ] 20'  (The ted.com format)
- [x] 60'  (Fun format)

### Pitch

A lot of fun, very few serious content and a lot of improvisation :) 

### Rock Star Check list

- [X] Create a new issue
- [ ] give it a shaky title
- [ ] indicate time slot (20' max) and a short description
- [ ] Assign all speakers
- [ ] select the milestone (qb-YYYYMMdd)
- [ ] select a label (Talk, Hands-On or Request, beginner ...etc)
- [ ] add a comment to the issue and add all talk materials (github repository, slides, running demos ...etc)
- [ ] add a comment to give us a feedback 

### Some advices

- Try to use simple words
- A picture better worth 1000 words
- KISS :kiss:
- try not to use lot of screen switch (we don't provide vomit bags)
- and more especially, have fun and try to interact with your audience.

**Comment by abderrazak-bouadma** [comment]
Hey there,

do you think that we can have a light version of the show ? like a 20' for example ?

**Comment by jefBinomed** [comment]
Not really, it's more like an animation rather than a talk. See with Siegfried, it's him who ask me to do SpeechLess Live during this session.

**Comment by abderrazak-bouadma** [comment]
The fact is that we'll finish too late and I'm not sure that the audience will remain until the end of the event. I'll see how to handle that.

**Comment by jefBinomed** [comment]
Check with Siegfried and tell me ;)

**Comment by abderrazak-bouadma** [comment]
I'll let @SiegfriedEhret deal with this subject, I already get in touch with him about that.
Thanks

**Comment by SiegfriedEhret** [comment]
Hello, 
@abderrazak-bouadma c'est une soirée spéciale, ça ne me choque pas du tout d'avoir plusieurs formats et que ça dure plus longtemps que d'habitude (d'après la milestone il y a en gros 1h15 de prez, avec le miam puis le speechless ça le fait).
Il faut juste vérifier que ça ne tombe pas pendant les grèves...
++
