### ISSUE TITLE
Spring for Apache Kafka

### ISSUE THREAD

**Issue by kokhanevych** [Sfeir/quarter-backs#56]
### Time slot

- [ ] 5'   (best to introduce a concept, a lib, an algorithm)
- [ ] 10'  (best to make a demo talk about a lib, an algorithm,)
- [X] 15'  (best to talk about any back subject with some slides and may be a lightening demo)
- [ ] 20'  (The ted.com format)

### Pitch

- What is Apache Kafka?
- Spring Boot + Apache Kafka Hello World Example
- Demo

### Rock Star Check list

- [X] Create a new issue
- [X] give it a shaky title
- [X] indicate time slot (20' max) and a short description
- [ ] Assign all speakers
- [ ] select the milestone (qb-YYYYMMdd)
- [ ] select a label (Talk, Hands-On or Request, beginner ...etc)
- [ ] add a comment to the issue and add all talk materials (github repository, slides, running demos ...etc)
- [ ] add a comment to give us a feedback 

### Some advices

- Try to use simple words
- A picture better worth 1000 words
- KISS :kiss:
- try not to use lot of screen switch (we don't provide vomit bags)
- and more especially, have fun and try to interact with your audience.

**Comment by abderrazak-bouadma** [comment]
Hello,
serais-tu dispo pour faire parler du sujet le 21 Aout prochain ?
