### ISSUE TITLE
Gagner des super pouvoirs avec le terminal

### ISSUE THREAD

**Issue by SiegfriedEhret** [Sfeir/quarter-backs#66]
### Time slot

- [ ] 5'   (best to introduce a concept, a lib, an algorithm)
- [ ] 10'  (best to make a demo talk about a lib, an algorithm,)
- [x] 15'  (best to talk about any back subject with some slides and may be a lightening demo)
- [ ] 20'  (The ted.com format)

### Pitch

Nous allons parcourir le monde merveilleux du terminal, en démarrant par le shell pour aller vers quelques applications bien pratiques comme abook, feh, fzf, httpie, pass, ranger, thefuck, tig..., et des tips qui feront de vous la seule personne capable d'utiliser votre ordinateur.

Note: je ne répondrais pas au débat ultime: (neo)vim vs emacs :-P

### Rock Star Check list

- [X] Create a new issue
- [x] give it a shaky title
- [x] indicate time slot (20' max) and a short description
- [x] Assign all speakers
- [ ] select the milestone (qb-YYYYMMdd)
- [x] select a label (Talk, Hands-On or Request, beginner ...etc)
- [ ] add a comment to the issue and add all talk materials (github repository, slides, running demos ...etc)
- [ ] add a comment to give us a feedback 

### Some advices

- Try to use simple words
- A picture better worth 1000 words
- KISS :kiss:
- try not to use lot of screen switch (we don't provide vomit bags)
- and more especially, have fun and try to interact with your audience.

**Comment by abderrazak-bouadma** [comment]
merci Sig, on se fait une soirée tools pour aout ?

**Comment by SiegfriedEhret** [comment]
Aller ! :smile:

**Comment by abderrazak-bouadma** [comment]
yo @SiegfriedEhret toujours d'accord pour le talk pour le 21 aout ?

**Comment by SiegfriedEhret** [comment]
Salut @abderrazak-bouadma, avec plaisir !
